---
title: "Schedule"
---

| Date                 | Topic                 | Lecture                                                        | Slides                                                                           | HW                                                         |                        Projects |
|:---------------------|:----------------------|:---------------------------------                              |:------------                                                                     |:------------                                               |                     -----------:|
| Tues Sept 6          | What is Data Science? | [What is Data Science?](what_is_ds_i.html)                     | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_i.pdf)        | [<i class="far fa-file-code fa-lg"></i>](homework_0.html)  |                                 |   
| Thur Sept 8          | Building blocks       | [Best Practices](best_practices.html)                          | [<i class="fas fa-desktop fa-lg"></i>](slides/best_practices.pdf)                |                                                            |                                 |
| Tues Sept 13         | Building blocks       | [Writing with Data](writing_with_data.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_with_data.pdf)             |                                                            |                                 |
| Thur Sept 15         | Building blocks       | [Git](git.html)                                                | [<i class="fas fa-desktop fa-lg"></i>](slides/git.pdf)                           | [<i class="far fa-file-code fa-lg"></i>](homework_1.html)  |                                 |   
| Tues Sept 20         | Data Wrangling I      | [Data Import](data_import.html)                                | [<i class="fas fa-desktop fa-lg"></i>](slides/data_import.pdf)                   |                                                            |                                 | 
| Thur Sept 22         | Data Wrangling I      | [Data Manipulation](data_manipulation.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/data_manipulation.pdf)             |                                                            |                                 | 
| Tues Sept 27         | Data Wrangling I      | [Tidy data](tidy_data.html)                                    | [<i class="fas fa-desktop fa-lg"></i>](slides/tidy_data.pdf)                     | [<i class="far fa-file-code fa-lg"></i>](homework_2.html)  |                                 |    
| Thur Sept 29         | Viz + EDA             | [Visualization 1](visualization_pt1.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 |                                                            |                                 | 
| Tues Oct 4           | Viz + EDA             | [Visualization 2](visualization_pt2.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 |                                                            |                                 | 
| Thur Oct 6           | Viz + EDA             | [EDA](exploratory_analysis.html)                               | [<i class="fas fa-desktop fa-lg"></i>](slides/exploratory_analysis.pdf)          | [<i class="far fa-file-code fa-lg"></i>](homework_3.html)  |                                 |    
| Tues Oct 11          | Case Study            | [Case study](what_is_ds_ii.html)                               | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_ii.pdf)       |                                                            |                                 | 
| Thur Oct 13          | Data Wrangling II     | [Reading Data from the Web](reading_data_from_the_web.html)    | [<i class="fas fa-desktop fa-lg"></i>](slides/reading_data_from_the_web.pdf)     |                                                            |                                 | 
| Tues Oct 18          | Data Wrangling II     | [Strings and Factors](strings_and_factors.html)                | [<i class="fas fa-desktop fa-lg"></i>](slides/strings_and_factors.pdf)           |                                                            | [Midterm](midterm_project.html) | 
| Thur Oct 20          | Interactivity         | [Making Websites](making_websites.html)                        | [<i class="fas fa-desktop fa-lg"></i>](slides/making_websites.pdf)               |                                                            |                                 | 
| Tues Oct 25          | Interactivity         | [Plot.ly and Dashboards](plotly_and_dashboards.html)           | [<i class="fas fa-desktop fa-lg"></i>](slides/plotly_and_dashboards.pdf)         | [<i class="far fa-file-code fa-lg"></i>](homework_4.html)  | [Final](final_project.html)     | 
| Thur Oct 27          | Iteration             | [Writing Functions](writing_functions.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_functions.pdf)             |                                                            |                                 | 
| Tues Nov 1           | Iteration             | [Iteration and Listcols](iteration_and_listcols.html)          | [<i class="fas fa-desktop fa-lg"></i>](slides/iteration_and_listcols.pdf)        |                                                            |                                 | 
| Thur Nov 3           | Iteration             | [Simulation](simulation.html)                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/simulation.pdf)                    | [<i class="far fa-file-code fa-lg"></i>](homework_5.html)  |                                 | 
| Tues Nov 8           | -Election day-        |                                                                |                                                                                  |                                                            |                                 | 
| Thur Nov 10          | Linear models         | [Linear Models](linear_models.html)                            | [<i class="fas fa-desktop fa-lg"></i>](slides/linear_models.pdf)                 |                                                            |                                 | 
| Tues Nov 15          | Linear models         | [Cross Validation](cross_validation.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/cross_validation.pdf)              |                                                            |                                 | 
| Thur Nov 27          | Linear models         | [Bootstrapping](bootstrapping.html)                            | [<i class="fas fa-desktop fa-lg"></i>](slides/bootstrapping.pdf)                 | [<i class="far fa-file-code fa-lg"></i>](homework_6.html)  |                                 | 
| Tues Nov 22          | -Thanksgiving-        |                                                                |                                                                                  |                                                            |                                 | 
| Thur Nov 24          | -Thanksgiving-        |                                                                |                                                                                  |                                                            |                                 | 
| Tues Nov 29          | Extra topics          | TBD                                                            |                                                                                  |                                                            |                                 | 
| Thur Dec 1           | Extra topics          | TBD                                                            |                                                                                  | [<i class="far fa-file-code fa-lg"></i>](homework_7.html)  |                                 | 
| Tues Dec 6           | -Final Project Week-  |                                                                |                                                                                  |                                                            |                                 | 
| Thur Dec 8           | -Final Project Week-  |                                                                |                                                                                  |                                                            |                                 | 
| Thur Dec 15          | Final Projects!       | [What is Data Science Revisited](what_is_ds_iii.html)          | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_iii.pdf)      |                                                            |                                 |
 